FROM python:3.6-alpine
ENV TZ=UTC
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /tmp/

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
 && echo $TZ > /etc/timezone \
 && mkdir /parser \
 && pip install -Ur /tmp/requirements.txt

COPY ./ /parser
WORKDIR /parser

CMD sh -c "celery -A run.app worker"
